[package]
name = "finite_field_encoding"
version = "0.1.0"
edition = "2021"

[dependencies]
field_element = { path = "./field_element" }
rand = "0.8.5"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"