[package]
name = "finite_field_encoding"
version = "0.1.0"
edition = "2021"

[dependencies]
field_element = { path = "./field_element" }
rand = "0.7"
ndarray = "0.13.0"
ndarray-linalg = "0.12.0"
ndarray-rand = "0.11.0"